twig_hooks:
    hooks:
        'app.base':
            content:
                template: 'base/content.html.twig'
#        'sylius_admin.book.create.content':
#            form:
#                component: 'App\Twig\Component\Book\BookFormComponent'
#                props:
#                    form: '@=_context.form'
#                    resource: '@=_context.resource'
        'sylius_admin.book.update.content':
            form:
                component: 'App\Twig\Component\Book\BookFormComponent'
                props:
                    form: '@=_context.form'
                    resource: '@=_context.resource'
